version: '3'

services:
  app:
    container_name: savings_calculator
    restart: always
    build: ./app
    command: streamlit run app.py

  nginx:
    container_name: nginx_savings_calculator
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
